# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutThisApp',
            fields=[
                ('sortorder', models.IntegerField(primary_key=True, serialize=False)),
                ('about_fld', models.TextField()),
                ('createdtime', models.DateTimeField(blank=True, null=True)),
                ('updatedtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_this_app',
            },
        ),
        migrations.CreateModel(
            name='Cilisting1',
            fields=[
                ('project_number', models.CharField(max_length=29)),
                ('project_description', models.CharField(blank=True, max_length=500, null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('planned_timing', models.DateField(blank=True, null=True)),
                ('revised_timing', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.IntegerField(blank=True, null=True)),
                ('savings_category', models.CharField(blank=True, max_length=211, null=True)),
                ('annual_savings_dollars', models.CharField(blank=True, max_length=20, null=True)),
                ('percent_complete', models.CharField(blank=True, max_length=26, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('originator', models.CharField(blank=True, max_length=31, null=True)),
                ('team', models.CharField(blank=True, max_length=600, null=True)),
                ('documents_complete', models.CharField(blank=True, max_length=3, null=True)),
                ('one_time_savings', models.CharField(blank=True, max_length=45, null=True)),
                ('hard_soft_savings', models.CharField(blank=True, max_length=9, null=True)),
                ('soft_dollars', models.CharField(blank=True, max_length=20, null=True)),
                ('il1_target_date', models.DateField(blank=True, null=True)),
                ('il2_target_date', models.DateField(blank=True, null=True)),
                ('il3_target_date', models.DateField(blank=True, null=True)),
                ('il4_target_date', models.DateField(blank=True, null=True)),
                ('il5_target_date', models.DateField(blank=True, null=True)),
                ('wc_idea_date', models.DateField(blank=True, null=True)),
                ('actual_implementation_date', models.DateField(blank=True, null=True)),
                ('enter_in_wc', models.CharField(blank=True, max_length=25, null=True)),
                ('area', models.CharField(blank=True, max_length=99, null=True)),
                ('updatedtime', models.DateTimeField()),
                ('id_wc', models.CharField(blank=True, max_length=10, null=True)),
                ('environmental', models.CharField(blank=True, max_length=23, null=True)),
                ('ease_of_implementation', models.CharField(blank=True, max_length=27, null=True)),
                ('submit', models.CharField(blank=True, max_length=10, null=True)),
                ('next_steps', models.CharField(blank=True, max_length=987, null=True)),
                ('suggestion_status', models.CharField(blank=True, max_length=99, null=True)),
                ('group', models.CharField(blank=True, max_length=99, null=True)),
                ('metric_impact', models.CharField(blank=True, max_length=77, null=True)),
                ('gift_4_suggestion', models.CharField(blank=True, max_length=10, null=True)),
                ('il_current', models.CharField(blank=True, max_length=1, null=True)),
                ('createdtime', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(max_length=567)),
                ('linkmore', models.CharField(max_length=9999)),
                ('display', models.CharField(max_length=11)),
                ('ciid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-ciid'],
                'db_table': 'cilisting1',
            },
        ),
    ]
